name: flexi_charts
description: A flexible and customizable charting library for Flutter, built from the ground up with CustomPainter for maximum customization and performance.
version: 0.0.1

# ADD THESE THREE LINES - Use your GitHub URL
homepage: https://github.com/dipendrasingh07062001/flexi_charts
repository: https://github.com/dipendrasingh07062001/flexi_charts
issue_tracker: https://github.com/dipendrasingh07062001/flexi_charts/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0